export const filmes = [
    {
        id: 1,
        titulo: "Interstellar",
        slug: "interstellar",
        fotoThumbnail: "../Imagens/Interstellar.avif",
        ano_lancamento: 2014,
        tipo: "f",
        genero: "Ficção Científica, Drama",
        elenco: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
        duracao: "2h 49min",
        nota_avaliacao: 8.6,
        numero_comentarios: 22300,
        faixa_etaria: "12+",
        indicacoes_premios: ["Oscar", "BAFTA"],
        sinopse:
            "Um grupo de astronautas viaja através de um buraco de minhoca em busca de um novo lar para a humanidade, enquanto a Terra enfrenta o colapso ambiental."
    },
    {
        id: 2,
        titulo: "Dark",
        slug: "dark",
        fotoThumbnail: "../Imagens/Dark.jpg",
        ano_lancamento: 2017,
        tipo: "s",
        temporadas: 3,
        genero: "Ficção Científica, Mistério",
        elenco: ["Louis Hofmann", "Lisa Vicari"],
        duracao: "1h",
        nota_avaliacao: 8.7,
        numero_comentarios: 18400,
        faixa_etaria: "16+",
        indicacoes_premios: ["Emmy Internacional"],
        sinopse:
            "Quatro famílias de uma pequena cidade alemã descobrem segredos obscuros e viagens no tempo, interligando passado, presente e futuro."
    },
];

export const filmes2 = [
    {
        id: 3,
        titulo: "Breaking Bad",
        slug: "breaking-bad",
        fotoThumbnail: "../Imagens/Breaking-Bad.jpg",
        ano_lancamento: 2008,
        tipo: "s",
        temporadas: 5,
        genero: "Drama, Crime",
        elenco: ["Bryan Cranston", "Aaron Paul"],
        duracao: "47min",
        nota_avaliacao: 9.5,
        numero_comentarios: 30200,
        faixa_etaria: "16+",
        indicacoes_premios: ["Emmy", "Globo de Ouro"],
        sinopse:
            "Um professor de química com câncer terminal se torna fabricante de metanfetamina para garantir o futuro financeiro de sua família."
    },
    {
        id: 4,
        titulo: "Gladiador",
        slug: "gladiador",
        fotoThumbnail: "../Imagens/Gladiador.png",
        ano_lancamento: 2000,
        tipo: "f",
        genero: "Ação, Drama",
        elenco: ["Russell Crowe", "Joaquin Phoenix"],
        duracao: "2h 35min",
        nota_avaliacao: 8.5,
        numero_comentarios: 9800,
        faixa_etaria: "16+",
        indicacoes_premios: ["Oscar"],
        sinopse:
            "Um general romano é traído e busca vingança como gladiador contra o imperador corrupto."
    },
];
export const filmesNum = [
    {
        id: 5,
        titulo: "Stranger Things",
        slug: "stranger-things",
        fotoThumbnail: "../Imagens/Stranger-Things.jpg",
        ano_lancamento: 2016,
        tipo: "s",
        temporadas: 5,
        genero: "Ficção Científica, Mistério",
        elenco: ["Millie Bobby Brown", "Finn Wolfhard"],
        duracao: "50min",
        nota_avaliacao: 8.8,
        numero_comentarios: 32000,
        faixa_etaria: "16+",
        indicacoes_premios: ["Emmy"],
        sinopse:
            "Em uma pequena cidade, crianças desaparecem misteriosamente, revelando experimentos secretos e criaturas sobrenaturais."
    },
    {
        id: 6,
        titulo: "The Witcher",
        slug: "the-witcher",
        fotoThumbnail: "../Imagens/The-Witcher.webp",
        ano_lancamento: 2019,
        tipo: "s",
        temporadas: 3,
        genero: "Fantasia, Ação",
        elenco: ["Henry Cavill", "Anya Chalotra"],
        duracao: "1h 5min",
        nota_avaliacao: 8.2,
        numero_comentarios: 21000,
        faixa_etaria: "16+",
        indicacoes_premios: [],
        sinopse:
            "Geralt de Rívia, um caçador de monstros, enfrenta forças sobrenaturais enquanto tenta encontrar seu lugar em um mundo turbulento."
    },
    {
        id: 7,
        titulo: "Narcos",
        slug: "narcos",
        fotoThumbnail: "../Imagens/Narcos.jpg",
        ano_lancamento: 2015,
        tipo: "s",
        temporadas: 3,
        genero: "Crime, Drama",
        elenco: ["Wagner Moura", "Pedro Pascal"],
        duracao: "50min",
        nota_avaliacao: 8.9,
        numero_comentarios: 27000,
        faixa_etaria: "18+",
        indicacoes_premios: [],
        sinopse:
            "A ascensão e queda do cartel de drogas de Pablo Escobar e o impacto de suas ações na Colômbia e no mundo."
    },
    {
        id: 8,
        titulo: "Umbrella Academy",
        slug: "umbrella-academy",
        fotoThumbnail: "../Imagens/Umbrella-Academy.webp",
        ano_lancamento: 2019,
        tipo: "s",
        temporadas: 3,
        genero: "Ação, Fantasia",
        elenco: ["Elliot Page", "Tom Hopper"],
        duracao: "50min",
        nota_avaliacao: 8.0,
        numero_comentarios: 15000,
        faixa_etaria: "16+",
        indicacoes_premios: [],
        sinopse:
            "Uma família disfuncional de super-heróis tenta impedir uma catástrofe iminente enquanto lida com suas próprias diferenças."
    },
    {
        id: 9,
        titulo: "Lucifer",
        slug: "lucifer",
        fotoThumbnail: "../Imagens/Lucifer.jpg",
        ano_lancamento: 2016,
        tipo: "s",
        temporadas: 6,
        genero: "Crime, Fantasia",
        elenco: ["Tom Ellis", "Lauren German"],
        duracao: "45min",
        nota_avaliacao: 8.1,
        numero_comentarios: 28000,
        faixa_etaria: "16+",
        indicacoes_premios: [],
        sinopse:
            "Lucifer Morningstar, o Diabo, abandona o Inferno e começa a ajudar a polícia de Los Angeles a resolver crimes enquanto explora sua própria redenção."
    },
    {
        id: 10,
        titulo: "La Casa de Papel",
        slug: "la-casa-de-papel",
        fotoThumbnail: "../Imagens/La-Casa-de-Papel.webp",
        ano_lancamento: 2017,
        tipo: "s",
        temporadas: 5,
        genero: "Crime, Suspense",
        elenco: ["Úrsula Corberó", "Álvaro Morte"],
        duracao: "50min",
        nota_avaliacao: 8.4,
        numero_comentarios: 40000,
        faixa_etaria: "16+",
        indicacoes_premios: [],
        sinopse:
            "Um grupo de criminosos altamente organizados realiza assaltos espetaculares à Casa da Moeda e ao Banco da Espanha."
    },
    {
        id: 11,
        titulo: "You",
        slug: "you",
        fotoThumbnail: "../Imagens/You.webp",
        ano_lancamento: 2018,
        tipo: "s",
        temporadas: 4,
        genero: "Suspense, Drama",
        elenco: ["Penn Badgley", "Victoria Pedretti"],
        duracao: "50min",
        nota_avaliacao: 7.9,
        numero_comentarios: 23000,
        faixa_etaria: "18+",
        indicacoes_premios: [],
        sinopse:
            "Joe Goldberg, obcecado por amor, usa redes sociais e sua inteligência para controlar a vida das pessoas ao seu redor."
    },
    {
        id: 12,
        titulo: "The Crown",
        slug: "the-crown",
        fotoThumbnail: "../Imagens/The-Crown.webp",
        ano_lancamento: 2016,
        tipo: "s",
        temporadas: 5,
        genero: "Drama, Histórico",
        elenco: ["Claire Foy", "Olivia Colman"],
        duracao: "55min",
        nota_avaliacao: 8.7,
        numero_comentarios: 19000,
        faixa_etaria: "14+",
        indicacoes_premios: ["Emmy"],
        sinopse:
            "A vida da Rainha Elizabeth II, desde seu casamento até os eventos que moldaram a monarquia britânica."
    },
    {
        id: 13,
        titulo: "Sex Education",
        slug: "sex-education",
        fotoThumbnail: "../Imagens/Sex-Education.jpeg",
        ano_lancamento: 2019,
        tipo: "s",
        temporadas: 4,
        genero: "Comédia, Drama",
        elenco: ["Asa Butterfield", "Gillian Anderson"],
        duracao: "50min",
        nota_avaliacao: 8.3,
        numero_comentarios: 15000,
        faixa_etaria: "14+",
        indicacoes_premios: [],
        sinopse:
            "Um adolescente e seus amigos enfrentam dilemas e descobertas sobre sexualidade e relacionamentos na escola."
    },
    {
        id: 14,
        titulo: "The Chosen",
        slug: "the-chosen",
        fotoThumbnail: "../Imagens/The-Chosen.jpeg",
        ano_lancamento: 2019,
        tipo: "s",
        temporadas: 3,
        genero: "Drama, Histórico, Religioso",
        elenco: ["Jonathan Roumie", "Shahar Isaac", "Elizabeth Tabish"],
        duracao: "50min",
        nota_avaliacao: 8.9,
        numero_comentarios: 12000,
        faixa_etaria: "Livre",
        indicacoes_premios: [],
        sinopse:
            "Uma série que retrata a vida de Jesus através dos olhos daqueles que o conheceram, explorando histórias e encontros com discípulos e pessoas comuns."
    },
    {
        id: 15,
        titulo: "Bridgerton",
        slug: "bridgerton",
        fotoThumbnail: "../Imagens/Bridgerton.webp",
        ano_lancamento: 2020,
        tipo: "s",
        temporadas: 3,
        genero: "Drama, Romance",
        elenco: ["Phoebe Dynevor", "Regé-Jean Page"],
        duracao: "50min",
        nota_avaliacao: 7.8,
        numero_comentarios: 12000,
        faixa_etaria: "14+",
        indicacoes_premios: [],
        sinopse:
            "Na alta sociedade londrina, famílias competem por poder e prestígio enquanto segredos e romances são revelados."
    },
    {
        id: 16,
        titulo: "Cobra Kai",
        slug: "cobra-kai",
        fotoThumbnail: "../Imagens/Cobra-Kai.webp",
        ano_lancamento: 2018,
        tipo: "s",
        temporadas: 6,
        genero: "Ação, Drama",
        elenco: ["Ralph Macchio", "William Zabka"],
        duracao: "30min",
        nota_avaliacao: 8.5,
        numero_comentarios: 18000,
        faixa_etaria: "14+",
        indicacoes_premios: [],
        sinopse:
            "Décadas após o torneio de Karatê de 1984, Johnny e Daniel retomam a rivalidade e treinam uma nova geração de lutadores."
    }
];
